#!/usr/bin/env bash
# configures an Ubuntu server with requirements

HOSTS_FILE="/etc/hosts"
TMP_FILE="/tmp/hosts.tmp"

# ensure script runs as root
if [ "$EUID" -ne 0 ]; then
  echo "please run as root"
  exit 1
fi

sed \
  -e '/^127\.0\.0\.1[[:space:]]\+localhost/d' \
  -e '/facebook\.com/d' \
  "$HOSTS_FILE" > "$TMP_FILE"


# add mappings
echo "127.0.0.2 localhost" >> "$TMP_FILE"
echo "8.8.8.8 facebook.com" >> "$TMP_FILE"

# replace hosts file
cp "$TMP_FILE" "$HOSTS_FILE"